### PR TITLE
Added new region constant for Germany

### PR DESCRIPTION
**Pull request by parvathy-u**

### CODE REVIEW

**Review by AnthonyOliveri — CHANGES_REQUESTED** [review]
Could you update the README as well to include this new region?

https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core#bmsclient

**Comment by parvathy-u** [comment]
Updated Readme file and alignment.

**Review by AnthonyOliveri — APPROVED** [review]

**Review by Aerex — DISMISSED** [review]
Changes look good to me

**Comment by Aerex** [comment]
BMSAnalytics, which is as a dependency to BMSCore, only pulls the latest 2.x version of BMSCore. We are currently on BMSCore 3.0.0. However, there is a critical bug that needs to be resolved in BMSCore 3.0.0 before we update BMSAnalytics. So until then we are unable to release a new version of cordova core plugin.

**Comment by Aerex** [comment]
Worked completed in [PR 32](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-core/pull/32)

**Pull request closed without merging**
